### ISSUE TITLE
[Request] A GLRetroView isReady() call, or an onReady() handler

### ISSUE THREAD

**Issue by tytydraco** [Swordfish90/LibretroDroid#19]
I'm trying to save my game state in my savedInstanceState Bundle upon configuration change to prevent game restarts. However, upon unserializing the state, I get a libc crash:

`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40 in tid 3552 (per.advancewars), pid 3552 (per.advancewars)`

It's due to the RetroView not existing for long enough. My workaround is to surround the unserializeState in a Thread that loops until it successfully restores the state, or a try count is reached. An isReady handler or just a isReady variable would be great.

**Comment by Swordfish90** [comment]
This is sadly not so straightforward. The main problem is that Libretro cores behave inconsistently and there is no clear threading model. In Lemuroid it's implemented exactly like that.

The closest thing you can get is the Rx event that the first frame has been rendered. Some cores, like ppsspp, while rendering the first frame, lazily initialize something that's required to restore states.

Also, the main problem is that states might be very big (like 25MB on ppsspp), so you can't put them in bundles or write them to files in a UI thread.

This might not be a problem for very old platforms, like nes or gameboy with states that are few KB.

**Comment by tytydraco** [comment]
I hadn't thought about that. Thanks for clarifying, I had previously saved my states in the main thread but I plan to move that to a background thread.
