### ISSUE TITLE
Audio cuts in and out when Bluetooth headphones are connected

### ISSUE THREAD

**Issue by tytydraco** [Swordfish90/LibretroDroid#30]
I suspect this issue is mainly due to the high audio latency when using Bluetooth headphones. If the latency gets too high, the audio cuts completely and the app crashes. I was able to replicate this issue in Lemuroid as well.

Let me know if you need any testing done. I realize this may be the fault of oboe, so feel free to close this issue if it's out of our control 👍

**Comment by Swordfish90** [comment]
You're probably right. It's very likely due to the buffering that LibretroDroid performs. Could you try to increase the buffer size in audio.cpp to see if the issue persists?

`fifo = std::make_unique<oboe::FifoBuffer>(2, roundToEven(sampleRate / 4));
audioBuffer = std::unique_ptr<int16_t[]>(new int16_t[sampleRate / 4]);`

to something like:

`fifo = std::make_unique<oboe::FifoBuffer>(2, roundToEven(sampleRate));
audioBuffer = std::unique_ptr<int16_t[]>(new int16_t[sampleRate]);`

Latency will be around 500ms, but if the audio stutter disappears we can study a smarter way.

**Comment by tytydraco** [comment]
Yep, that seems to have fixed the issue. What approach could we take on this? Could we add some form of latency constraint detection to loosen the buffer size if we are dropping audio? I'm not huge on audio dev but I'm open to learning. If you've got an idea, let me know and I can try working on it.

**Comment by Swordfish90** [comment]
Ok, we have proof that's my fault :smile:. I guess we have two real options:

1) Changing our buffer size depending on the size of the underlying audio buffer. This requires reinitializing the audiobuffer when we detect that we're requesting "too many" frames in the callback. It's a bit of a mess to implement and might increase latency.

2) Forcing the number of frames inside the callback with [setFramesPerCallback](https://google.github.io/oboe/reference/classoboe_1_1_audio_stream_builder.html#a3f397821f61eabaeedaf31064c859a54). This way we force the callback to request a known number of frames which is much lower than our buffer capacity (let's say 1/4 or 1/8 but the value might need to be tweaked). This means that the oboe will not be able to optimize the buffer size based on latency, but I don't think it will be a major problem for emulators.

If you want, give 2 a go and let me know if it still works on your usecase.

**Comment by tytydraco** [comment]
Gave 2 a shot, here's what I can report:

I added this line to the Audio initialization and replaced <divisor> with a few values:
`builder.setFramesPerCallback(roundToEven(sampleRate / <divisor>));`

- If I set divisor to 4, audio cuts in and out.
- If I set it to 16, the audio is mostly consistent.
- If I set it to 32, the audio is amazing. Beautiful and consistent, and latency is still perfecto.

Setting it to just `sampleRate` with no divisor made the latency pretty bad but did improve the audio consistency.

I also experimented with changing the `sampleRate / 4` part to something like `sampleRate / 8`. The latency **significantly** improved. 

Trying `sampleRate / 16`  slightly improved latency compared to `sampleRate / 8` but it causes the audio to break up.

`sampleRate / 12` is perfect.

I think 125ms is a bit too lenient and possibly too noticeable. 

I'll make a pull request for the changes I made so you can look them over. They improved the audio a lot for me.

P.S.: When connecting/disconnecting my Bluetooth headphones, the audio breaks, and the app needs to be restarted. This is probably a different issue though.
