### ISSUE TITLE
Emulator doubles it's speed on GLRetroView recreation

### ISSUE THREAD

**Issue by tytydraco** [Swordfish90/LibretroDroid#36]
This is very weird but it's been happening for quite some time. I'm not *entirely* sure it's an issue with LibretroDroid but I would like to see if you have the same issue.

https://photos.app.goo.gl/1hGLzPDNwysmZQF4A

Notice that on rotate, it works fine, but on rotate back to portrait, it loses sync. I tested this w/o saving states, same issue.

Does this happen to you (without configChanges="orientation|screenSize")? If not, I'll close this.

**Comment by tytydraco** [comment]
Oh and this isn't fast forwarding either. If you enable FF while this bug happens, it's like 4x.

**Comment by Swordfish90** [comment]
I'm not able to access the video (google photo said "it will be availalbe in moment" hours ago :smile:) but I think I understand the problem.

I'm not able to reproduce with the configChange, but I think something is leaking and you have multiple calls to LibretroDroid.step(), causing the application to go faster.

**Comment by tytydraco** [comment]
Ah, I see. It must be on my end then. I'll take a look 👍

**Comment by tytydraco** [comment]
I don't think something is leaking since the fragments containing the GLRetroViews are destroyed on each configuration change. I am also replacing the views in the fragment manager, not adding them, so there can only be one in existence at a time.

**Comment by tytydraco** [comment]
Updating again, I tried removing all fragments in my entire project and yet it still occurs.

**Comment by tytydraco** [comment]
Ready for the kicker? It was because I apply immersive mode to the view. That's what somehow caused this issue.

```
    private fun immersive() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            with (window.insetsController!!) {
                hide(
                    WindowInsets.Type.statusBars() or
                    WindowInsets.Type.navigationBars()
                )
                systemBarsBehavior = WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
            }
        } else {
            window.decorView.systemUiVisibility = (
                View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY or
                View.SYSTEM_UI_FLAG_LAYOUT_STABLE or
                View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or
                View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN or
                View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or
                View.SYSTEM_UI_FLAG_FULLSCREEN
            )
        }
    }
```

```
override fun onWindowFocusChanged(hasFocus: Boolean) {
        super.onWindowFocusChanged(hasFocus)

        if (!hasFocus)
            return

        /* Reapply our immersive mode again */
        immersive()
    }
```

```
/* Make sure we reapply immersive mode on rotate */
        window.decorView.setOnApplyWindowInsetsListener { _, windowInsets ->
            Handler(Looper.getMainLooper()).postDelayed({
                immersive()
            }, 200)
            return@setOnApplyWindowInsetsListener windowInsets
        }
```
