### ISSUE TITLE
GLES failure try catch?

### ISSUE THREAD

**Issue by tytydraco** [Swordfish90/LibretroDroid#40]
I saw your commit earlier about adding internal error handling to the libretro cores, and one of them was the GLES failure. I got this exception on an Android Fire TV stick:

` abort_message: assertion "terminating with uncaught exception of type std::runtime_error: Cannot create gl program"`

Is it possible that this exception is unhandled, or is this on my end?

**Comment by Swordfish90** [comment]
It looks like an OpenGL issue (so something that should be handled LibretroDroid side). Are you able to reproduce it with every shader, or is it specific to one shader?

**Comment by tytydraco** [comment]
Looks like it happens with every shader. It's an old fire tv stick so it's probably an exception handler not catching the GLES incompatibility.
