### ISSUE TITLE
Crash on re-adding view to another parent

### ISSUE THREAD

**Issue by tytydraco** [Swordfish90/LibretroDroid#53]
This is more of a question than a bug. Is the GLRetroView dependent on the view it was added to, or can I remove the view from it's parent and add it to another view? I am trying to make the GLRetroView persist in an MVVM ViewModel.

**Comment by Swordfish90** [comment]
Sorry, I've never tried that so I can't give you a definitive answer. I'd not bet a lot of money on it though, there is a lot going on including the lifecycle observers and the OpenGL state.
