### ISSUE TITLE
PPSSPP renders black only

### ISSUE THREAD

**Issue by JustMeDaFaq** [Swordfish90/LibretroDroid#58]
Hi,
PPSSPP shows an black screen only. It does put out sound tho, tested with latest libretrodroid and latest ppsspp from
http://buildbot.libretro.com/nightly/android/latest/arm64-v8a/
(without the ppsspp files added)

**Comment by JustMeDaFaq** [comment]
Older version of the core seems to work, might be an core issue?

**Comment by JustMeDaFaq** [comment]
Sorry for spamming, but it seems that in the up to date core, it falls back to software renderer for whatever reason:
01-25 23:00:29.790 23943 23987 D LibretroDroid: Called RETRO_ENVIRONMENT_GET_SAVE_DIRECTORY
01-25 23:00:29.790 23943 23987 D LibretroDroid: Called RETRO_ENVIRONMENT_GET_PREFERRED_HW_RENDER
01-25 23:00:29.790 23943 23987 I Libretro Core: [SYSTEM] Using Software backend

**Comment by Swordfish90** [comment]
Hi @JustMeDaFaq, sadly the latest PPSSPP has some issues. For starters it ignores the GLSL supported renderer exposed by LibretroDroid (leading to the black screens you experienced), then it always exposes 60hz while forcing unthrottled mode, so 30Hz games effectively run at doubled speed.

These are not really LibretroDroid issues, but I need to find the time to open them on the upstream repo. For the moment you can find a recent version of the core patched by me here:

https://github.com/Swordfish90/LemuroidCores/

**Comment by JustMeDaFaq** [comment]
Thanks for the explanation and the prebuild lib.
Just fmi, is 

> coreParam.unthrottle = true;

 the reason it runs double as fast?

**Comment by xiejinglan** [comment]
> Thanks for the explanation and the prebuild lib.
> Just fmi, is
> 
> > coreParam.unthrottle = true;
> 
> the reason it runs double as fast?

i found a way to fix this bug

**Comment by DRFR33MAN24** [comment]
I'm having a similar issue with self added core for PS2, can you please refer to the ppsspp fork ( the one where you modified the renderer to be compatible with libretrodroid), cause I can't find source code for any of the cores bundled with lemuroid, just prebuilt binaries.
