### ISSUE TITLE
ppsspp_libretro_android.so

### ISSUE THREAD

**Issue by xiejinglan** [Swordfish90/LibretroDroid#61]
hello , i download ppsspp_libretro_android.so from  buildbot, and it's does't work on libretrodroid . I want to know why! Would you please tell me.

**Comment by JustMeDaFaq** [comment]
Hi, can you provide any log?
Made sure you got the right architectures library file for your android device?

PPSSPP is definetly working, tho, PPSSPP expect the frontend to be synced to audio blocks, which isnt currently implemented in libretrodroid. So games could run a bit fast
