### ISSUE TITLE
GLRetroView addObserver doesn't work in androidx.lifecycle 2.3.0

### ISSUE THREAD

**Issue by tytydraco** [Swordfish90/LibretroDroid#62]
Hey again! Long time no see. No big deal, but when reviving my project Ludere, I noticed that upgrading

`implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.2.0'`

to

`implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.0'`

broke input for GLRetroView. I assume this has something to do with lifecycle.addObserver().

Just wanted to let you know, as it was a HUGE headache for me haha! Hope you're doing well.

**Comment by Swordfish90** [comment]
Hi @tytydraco . I'm doing good, what about you? Thank you also for the reddit post :smile:.

I'll look into this, probably mixing lifecycle versions creates some kind of issues. I'll try to see if we can abstract that away somehow.

**Comment by Swordfish90** [comment]
I have been able to reproduce the issue. The fix has already landed with #74 .
