### ISSUE TITLE
Compile and consult

### ISSUE THREAD

**Issue by clondy999** [Swordfish90/LibretroDroid#68]
I use Android studio to compile, but I always report errors. Do you have specific compilation instructions?

**Comment by clondy999** [comment]
![image](https://user-images.githubusercontent.com/73311186/119672453-3122a980-be6d-11eb-8089-7cda615e69bb.png)

**Comment by Swordfish90** [comment]
Hi @clondy999, you should not put the application dependencies in that block, but they go inside the application module.

You can check the included sample on how to get started with a minimal application: https://github.com/Swordfish90/LibretroDroid/tree/master/app 

If you're looking for cores I suggest you to take a look here to reduce compatibility issues: https://github.com/Swordfish90/LemuroidCores

There is not a lot of documentation at the moment, but if you'd like to contribute a couple of lines, I'll gladly add them to the wiki.
