### ISSUE TITLE
add additional snes9x cores?

### ISSUE THREAD

**Issue by stspdotname** [Swordfish90/LibretroDroid#71]
The default snes9x core suffers from stuttering audio on my phone (fairphone2) to the point where it is more comfortable to play games without sound.

libretro does offer a couple of alternative snes9x cores:

- snes9x2002
- snes9x2005
- snes9x2005_plus
- snes9x2010

The snes9x2002 core in particular may yield better results on low performance devices (better in terms of playability, not in terms of emulation accuracy).

RetroPie offers multiple snes9x cores in order to accommodate low spec machines such as the Pi Zero.
It would be nice if Lemuroid did this, too.

Just a humble request.  I am very impressed with the quality of Lemuroid overall.  Cheers :)

**Comment by JustMeDaFaq** [comment]
That's probably something you want to report at https://github.com/Swordfish90/Lemuroid

Since this repo here isnt for Lemuroid but it's underlying frontend library. Which cores are used isn't part of this repo :)

**Comment by stspdotname** [comment]
Ooops, yes, looks like I filed this against the wrong repository. My intention was to file an issue against the LemuroidCores repo. My bad.
