### ISSUE TITLE
onDestroy() Crash in 0.6.0

### ISSUE THREAD

**Issue by tytydraco** [Swordfish90/LibretroDroid#81]
https://pastebin.com/mFq3PwLX
ndk-stack ^

Also, it didn't throw a java exception, it just segfaulted, so that try-catch doesn't work either :(

**Comment by tytydraco** [comment]
Correction: Environment->deinitialize is the error point, smth with strlen()

**Comment by Swordfish90** [comment]
Thank you for spotting it. It was another dumb mistake.
